qc:
  threads: 8

trim:
  threads: 8
  adapter: "AGATCGGAAGAGC"

align:
  threads: 16

methylation:
  threads: 12

dss:
  threads: 4
  smoothing: TRUE
  smoothing_span: 500
  delta: 0.1
  p_threshold: 0.001
